import { ethers } from "ethers";

// Contract addresses - update after deployment
// These are loaded from deployment.json or set via environment variables
const ADDRESSES = {
  InvoiceToken: import.meta.env.VITE_INVOICE_TOKEN_ADDRESS || "",
  FundingPool: import.meta.env.VITE_FUNDING_POOL_ADDRESS || "",
  OracleGateway: import.meta.env.VITE_ORACLE_GATEWAY_ADDRESS || "",
};

// Minimal ABIs (key functions only - full ABIs generated by Hardhat compile)
const InvoiceTokenABI = [
  "function mintInvoice(uint256 _faceValue, uint256 _totalShares, uint256 _discountBps, uint256 _dueDate, string _metadataURI) external returns (uint256)",
  "function getInvoice(uint256 _tokenId) external view returns (tuple(uint256 tokenId, address issuer, uint256 faceValue, uint256 totalShares, uint256 sharePrice, uint256 dueDate, uint256 createdAt, string metadataURI, uint8 state))",
  "function getAllInvoiceIds() external view returns (uint256[])",
  "function getInvoiceCount() external view returns (uint256)",
  "function cancelInvoice(uint256 _tokenId) external",
  "function uri(uint256 _tokenId) external view returns (string)",
  "event InvoiceCreated(uint256 indexed tokenId, address indexed issuer, uint256 faceValue, uint256 totalShares, uint256 sharePrice, uint256 dueDate, string metadataURI)",
  "event InvoiceStateChanged(uint256 indexed tokenId, uint8 newState)",
];

const FundingPoolABI = [
  "function fundInvoice(uint256 _tokenId) external payable",
  "function claimFunds() external",
  "function fundingInfo(uint256) external view returns (uint256 totalFunded, uint256 targetAmount, uint256 investorCount, bool settled)",
  "function investorStakes(uint256, address) external view returns (uint256)",
  "function investorShares(uint256, address) external view returns (uint256)",
  "function claimableBalance(address) external view returns (uint256)",
  "function getInvestors(uint256 _tokenId) external view returns (address[])",
  "event InvoiceFunded(uint256 indexed tokenId, address indexed investor, uint256 amount, uint256 shares)",
  "event InvoiceFullyFunded(uint256 indexed tokenId, uint256 totalAmount)",
  "event InvoiceSettled(uint256 indexed tokenId, uint256 totalDistributed)",
  "event FundsClaimed(address indexed investor, uint256 amount)",
];

const OracleGatewayABI = [
  "function isPaymentConfirmed(uint256 _tokenId) external view returns (bool)",
  "event PaymentConfirmed(bytes32 indexed requestId, uint256 indexed tokenId, bytes32 proofHash)",
  "event SettlementTriggered(uint256 indexed tokenId)",
];

// State labels
export const INVOICE_STATES = ["Open", "Funded", "Settled", "Defaulted", "Cancelled"];
export const STATE_COLORS = {
  0: "#22c55e", // Open - green
  1: "#3b82f6", // Funded - blue
  2: "#8b5cf6", // Settled - purple
  3: "#ef4444", // Defaulted - red
  4: "#6b7280", // Cancelled - gray
};

// Connect wallet
export async function connectWallet() {
  if (!window.ethereum) throw new Error("MetaMask not installed");
  const provider = new ethers.BrowserProvider(window.ethereum);
  await provider.send("eth_requestAccounts", []);
  const signer = await provider.getSigner();
  const address = await signer.getAddress();
  const network = await provider.getNetwork();
  return { provider, signer, address, chainId: Number(network.chainId) };
}

// Get contract instances
export function getContracts(signerOrProvider) {
  return {
    invoiceToken: new ethers.Contract(ADDRESSES.InvoiceToken, InvoiceTokenABI, signerOrProvider),
    fundingPool: new ethers.Contract(ADDRESSES.FundingPool, FundingPoolABI, signerOrProvider),
    oracleGateway: new ethers.Contract(ADDRESSES.OracleGateway, OracleGatewayABI, signerOrProvider),
  };
}

// Fetch all invoices with funding info
export async function fetchAllInvoices(contracts) {
  const ids = await contracts.invoiceToken.getAllInvoiceIds();
  const invoices = [];

  for (const id of ids) {
    const inv = await contracts.invoiceToken.getInvoice(id);
    const funding = await contracts.fundingPool.fundingInfo(id);

    invoices.push({
      tokenId: Number(inv.tokenId),
      issuer: inv.issuer,
      faceValue: inv.faceValue,
      totalShares: Number(inv.totalShares),
      sharePrice: inv.sharePrice,
      dueDate: new Date(Number(inv.dueDate) * 1000),
      createdAt: new Date(Number(inv.createdAt) * 1000),
      metadataURI: inv.metadataURI,
      state: Number(inv.state),
      totalFunded: funding.totalFunded,
      targetAmount: funding.targetAmount,
      investorCount: Number(funding.investorCount),
      settled: funding.settled,
    });
  }

  return invoices;
}

// Upload metadata to IPFS via backend
export async function uploadToIPFS(file) {
  const formData = new FormData();
  formData.append("file", file);

  const response = await fetch("/api/ipfs/upload", {
    method: "POST",
    body: formData,
  });

  if (!response.ok) throw new Error("IPFS upload failed");
  return response.json(); // { cid, url }
}

// Pin metadata JSON to IPFS via backend
export async function pinMetadata(metadata) {
  const response = await fetch("/api/ipfs/metadata", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(metadata),
  });

  if (!response.ok) throw new Error("Metadata pin failed");
  return response.json(); // { cid, url }
}

export { ADDRESSES };
